import { ArtEvent } from './eventTypes';

// Sample events for development/demo — replace with scraped data
export const SAMPLE_EVENTS: ArtEvent[] = [
  {
    id: '1',
    title: 'NSO國家交響樂團音樂會',
    start: '2026-06-07',
    end: '2026-06-07',
    category: 'classical',
    venue: '國家兩廳院',
    city: 'Taipei',
    url: 'https://npac-ntch.org',
    description: '國家交響樂團定期音樂會',
  },
  {
    id: '2',
    title: '魏如萱演唱會',
    start: '2026-06-13',
    end: '2026-06-13',
    category: 'pop',
    venue: '北部流行音樂中心',
    city: 'Taipei',
    url: 'https://northflow.org.tw',
  },
  {
    id: '3',
    title: '表演工作坊《暗戀桃花源》',
    start: '2026-06-20',
    end: '2026-06-28',
    category: 'theater',
    venue: '國家兩廳院',
    city: 'Taipei',
    url: 'https://npac-ntch.org',
  },
  {
    id: '4',
    title: '雲門舞集春季公演',
    start: '2026-06-05',
    end: '2026-06-08',
    category: 'dance',
    venue: '國家歌劇院',
    city: 'Taichung',
    url: 'https://npac-ntt.org',
  },
  {
    id: '5',
    title: '當代水墨聯展',
    start: '2026-06-01',
    end: '2026-06-30',
    category: 'exhibition',
    venue: '台北表演藝術中心',
    city: 'Taipei',
  },
  {
    id: '6',
    title: '歌仔戲精選《白蛇傳》',
    start: '2026-06-14',
    end: '2026-06-15',
    category: 'traditional',
    venue: '衛武營國家藝術文化中心',
    city: 'Kaohsiung',
    url: 'https://npac-weiwuying.org',
  },
  {
    id: '7',
    title: '威爾第《奧泰羅》',
    start: '2026-06-19',
    end: '2026-06-21',
    category: 'opera',
    venue: '國家歌劇院',
    city: 'Taichung',
    url: 'https://npac-ntt.org',
  },
  {
    id: '8',
    title: '即興劇工作坊',
    start: '2026-06-10',
    category: 'workshop',
    venue: '桃園市文化局',
    city: 'Taoyuan',
  },
  {
    id: '9',
    title: '新竹市交響樂團音樂會',
    start: '2026-06-25',
    category: 'classical',
    venue: '新竹市文化局演藝廳',
    city: 'Hsinchu',
    url: 'https://hcccb.gov.tw',
  },
];
